#!/bin/bash

sudo apt update -y

sudo apt install apt-transport-https ca-certificates curl software-properties-common -y

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" -y

sudo apt update -y

apt-cache policy docker-ce -y

sudo apt install docker-ce -y

sudo chmod 777 /var/run/docker.sock







::: NOTE :::
1. To run this shellscript first create a shellscript file using vi editor by running the command   << vi docker_install.sh >>  and paste the code above
2. Now run this command to give execute permission to the shellscript file::  sudo chown 777 docker_install.sh
3. Now run the shellscript with command::    sh docker_install.sh
