#!/bin/bash

sudo apt install openjdk-11-jre -y

curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee \
  /usr/share/keyrings/jenkins-keyring.asc > /dev/null

echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
  https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
  /etc/apt/sources.list.d/jenkins.list > /dev/null

sudo apt-get update -y

sudo apt-get install jenkins -y

sudo systemctl enable jenkins

sudo systemctl start jenkins

sudo systemctl status jenkins

sudo cat /var/lib/jenkins/secrets/initialAdminPassword





=========================================================================================================================================================================
::: NOTE :::
1. To run this shellscript first create a shellscript file using vi editor by running the command   << vi jenkins_install.sh >>  and paste the code above
2. Now run this command to give execute permission to the shellscript file::  sudo chmod +x jenkins_install.sh
3. Now run the shellscript with command::    sh jenkins_install.sh
